markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'space_after_headers']

permalink: /:year/:month/:day.html
exclude: [Gemfile, Gemfile.lock, LICENSE, README.md, CNAME]
category-list: [ruby, linux, JS, 项目管理]
safe: false