markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'space_after_headers']

permalink: /:categories/:year/:month/:day.html
exclude: [Gemfile, Gemfile.lock, LICENSE, README.md, CNAME]
category-list: [ruby, linux, javascript, pm]
safe: false