markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'space_after_headers']

permalink: /:year/:month/:day/:title.html
exclude: [Gemfile, Gemfile.lock, LICENSE, README.md, CNAME]
category-list: [后台技术, 运维, 前端技术, 设计模式, 感悟]
safe: false
#pygments: true
highlighter: pygments
url: http://www.songyuchao.com
comments:
  provider: duoshuo
  disqus:
    short_name: jacksong
  livefyre :
    site_id : 123
  duoshuo :
    name : jacksong
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light
